const LegalNotice = require('../models/LegalNotice');
const Case = require('../models/Case');
const { AppError } = require('../middleware/errorHandler');
const { getPagination } = require('../utils/helpers');
const { TIMELINE_EVENTS } = require('../utils/constants');
const { generateLegalNotice } = require('../services/documentService');

// @desc    Generate a legal notice using AI
// @route   POST /api/notices/generate
// @access  Private
const createNotice = async (req, res, next) => {
  try {
    const {
      sender,
      recipient,
      subject,
      incidentDescription,
      legalClaim,
      desiredResolution,
      deadline,
      language,
      caseId,
    } = req.body;

    // Validation
    if (!sender || !sender.name || !sender.address) {
      return next(new AppError('Sender name and address are required', 400));
    }
    if (!recipient || !recipient.name || !recipient.address) {
      return next(new AppError('Recipient name and address are required', 400));
    }
    if (!subject) return next(new AppError('Notice subject is required', 400));
    if (!incidentDescription) return next(new AppError('Incident description is required', 400));
    if (!legalClaim) return next(new AppError('Legal claim is required', 400));
    if (!desiredResolution) return next(new AppError('Desired resolution is required', 400));
    if (!deadline) return next(new AppError('Response deadline is required', 400));

    const userLanguage = language || req.user.language || 'en';

    console.log(`📜 Generating legal notice for ${req.user.name}...`);

    // Generate notice via AI
    const { generatedNotice, provider, category } = await generateLegalNotice(
      { sender, recipient, subject, incidentDescription, legalClaim, desiredResolution, deadline },
      userLanguage
    );

    // Save to database
    const notice = await LegalNotice.create({
      userId: req.user.id,
      caseId: caseId || null,
      sender,
      recipient,
      subject,
      incidentDescription,
      legalClaim,
      desiredResolution,
      deadline,
      generatedNotice,
      generatedBy: provider,
      category: category || 'Other',
      language: userLanguage,
      status: 'generated',
    });

    // Link to case if provided
    if (caseId) {
      const caseDoc = await Case.findById(caseId);
      if (caseDoc) {
        caseDoc.timeline.push({
          event: TIMELINE_EVENTS.NOTICE_GENERATED,
          description: `Legal notice "${subject}" generated by JurisPilot`,
          performedBy: req.user.id,
        });
        await caseDoc.save();
      }
    }

    console.log(`   ✅ Notice generated by ${provider}`);

    res.status(201).json({
      success: true,
      message: '📜 Legal notice generated by JurisPilot!',
      data: notice,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get all user's notices
// @route   GET /api/notices
// @access  Private
const getMyNotices = async (req, res, next) => {
  try {
    const { page, limit, skip } = getPagination(req.query.page, req.query.limit);
    const { status, caseId } = req.query;

    const filter = { userId: req.user.id };
    if (status) filter.status = status;
    if (caseId) filter.caseId = caseId;

    const total = await LegalNotice.countDocuments(filter);
    const notices = await LegalNotice.find(filter)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .select('-generatedNotice -__v'); // Exclude full notice text in list view

    res.status(200).json({
      success: true,
      count: notices.length,
      total,
      page,
      pages: Math.ceil(total / limit),
      data: notices,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single notice with full generated text
// @route   GET /api/notices/:id
// @access  Private
const getNoticeById = async (req, res, next) => {
  try {
    const notice = await LegalNotice.findOne({
      _id: req.params.id,
      userId: req.user.id,
    });

    if (!notice) {
      return next(new AppError('Legal notice not found', 404));
    }

    res.status(200).json({
      success: true,
      data: notice,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Regenerate a legal notice
// @route   PUT /api/notices/:id/regenerate
// @access  Private
const regenerateNotice = async (req, res, next) => {
  try {
    const { language } = req.body;

    const notice = await LegalNotice.findOne({
      _id: req.params.id,
      userId: req.user.id,
    });

    if (!notice) {
      return next(new AppError('Legal notice not found', 404));
    }

    const userLanguage = language || notice.language || 'en';

    console.log(`🔄 Regenerating notice: ${notice.subject}`);

    const { generatedNotice, provider } = await generateLegalNotice(
      {
        sender: notice.sender,
        recipient: notice.recipient,
        subject: notice.subject,
        incidentDescription: notice.incidentDescription,
        legalClaim: notice.legalClaim,
        desiredResolution: notice.desiredResolution,
        deadline: notice.deadline,
      },
      userLanguage
    );

    notice.generatedNotice = generatedNotice;
    notice.generatedBy = provider;
    notice.language = userLanguage;
    notice.status = 'generated';

    await notice.save();

    res.status(200).json({
      success: true,
      message: '🔄 Legal notice regenerated!',
      data: notice,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update notice status (mark as reviewed/sent)
// @route   PUT /api/notices/:id/status
// @access  Private
const updateNoticeStatus = async (req, res, next) => {
  try {
    const { status } = req.body;

    if (!['draft', 'generated', 'reviewed', 'sent'].includes(status)) {
      return next(new AppError('Invalid status. Use: draft, generated, reviewed, sent', 400));
    }

    const notice = await LegalNotice.findOneAndUpdate(
      { _id: req.params.id, userId: req.user.id },
      { status },
      { new: true }
    );

    if (!notice) {
      return next(new AppError('Legal notice not found', 404));
    }

    res.status(200).json({
      success: true,
      message: `Notice status updated to "${status}"`,
      data: notice,
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete a notice
// @route   DELETE /api/notices/:id
// @access  Private
const deleteNotice = async (req, res, next) => {
  try {
    const notice = await LegalNotice.findOneAndDelete({
      _id: req.params.id,
      userId: req.user.id,
    });

    if (!notice) {
      return next(new AppError('Legal notice not found', 404));
    }

    res.status(200).json({
      success: true,
      message: 'Legal notice deleted successfully',
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  createNotice,
  getMyNotices,
  getNoticeById,
  regenerateNotice,
  updateNoticeStatus,
  deleteNotice,
};